[package]
name = "image-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
image = "0.24"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["ImageData"] } 